---
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  status:
    project:
      default:
        target: auto
comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false
