---
project_name: dashboard
version: 2

release:
  github:
    owner: n3tuk
    name: dashboard
  name_template: |-
    {{ .Version }}
changelog:
  disable: true
snapshot:
  version_template: >-
    {{ incpatch .Version }}~d{{ .Now.Format "0601021504" }}
checksum:
  name_template: |-
    dashboard-sha512
  algorithm: sha3-512

builds:
  - id: dashboard
    main: main.go
    binary: dashboard
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    ldflags: >-
      -s -w
      -X 'main.Branch={{ .Branch }}'
      -X 'main.Commit={{ .ShortCommit }}'
      -X 'main.Version={{ .Version }}'
      -X 'main.BuildDate={{ .Date }}'
      -X 'main.Architecture={{ .Runtime.Goarch }}'
    asmflags: >-
      all=-trimpath=.
    gcflags: >-
      all=-trimpath=.
    goos:
      - 'linux'
      - 'darwin'
      - 'windows'
    goarch:
      - 'arm64'
      - 'amd64'
    goarm:
      - '7'
    goamd64:
      - 'v3'
    ignore:
      - goos: darwin
        goarch: amd64

archives:
  - id: archive
    name_template: |-
      {{ .ProjectName }}-v{{ .Version }}-{{ tolower .Os }}-{{ tolower .Arch }}
    format: zip
    builds_info:
      group: root
      owner: root
      mode: 0755
      mtime: 2006-01-02T15:04:05Z
    files:
      - LICENSE

dockers:
  - id: amd64
    goarch: amd64
    goamd64: v3
    image_templates:
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-amd64
    dockerfile: Dockerfile
    use: docker
    skip_push: false
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

  - id: arm64
    goarch: arm64
    goarm: 7
    image_templates:
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-arm64
    dockerfile: Dockerfile
    use: docker
    skip_push: false
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

# Build a set of manifests based on all the ways the GitHub Action could be
# called, including as the main branch, both short and long commit IDs, and each of
# Major, Major/Minor, and Major/Minor/Patch versions being tagged
docker_manifests:
  - id: latest
    name_template: ghcr.io/n3tuk/dashboard:latest
    use: docker
    skip_push: auto
    image_templates:
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-amd64
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-arm64

  - id: major
    name_template: ghcr.io/n3tuk/dashboard:v{{ .Major }}
    use: docker
    skip_push: auto
    image_templates:
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-amd64
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-arm64

  - id: version
    name_template: ghcr.io/n3tuk/dashboard:v{{ .Version }}
    use: docker
    skip_push: auto
    image_templates:
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-amd64
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-arm64

  - id: commit
    name_template: ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}
    use: docker
    skip_push: false
    image_templates:
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-amd64
      - ghcr.io/n3tuk/dashboard:{{ .ShortCommit }}-arm64
